enzimas = {
    'EcoRI' : 'GAATTC',
    'BamHI' : 'GGATCC',
    'HindIII' : 'AAGCTT', 
    'PstI' : 'CTGCAG',
    'XhoI' : 'CTCGAG',
    'SalI' : 'GTCGAC',
    'SmaI' : 'CCCGGG',
    'NotI' : 'GCGGCCGC',
    'NdeI' : 'CATATG',
    'NcoI' : 'CCATGG',
}

genes_resistencia = {
    bla : 'B-Lactamase',
    nptII : 'Kanamicina',
    cat : 'Clorafenicol',
}

bla = ['''ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAACG
CTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGAT
CCTTGAGAGTTTTCGCCCCGAAGTTTGCGCGGTCATGTGCGCAGCGGTCGGGCTGAACAGCTTGCTGGTGAAAAGTTTGA
GGGGACGATGTCACTGGCTGAGCACAAACGGTGTAACGGGATCTTCACCTAGATCCTTTTTGATAATCTCATGACCAAAA
TCCGTTTGATTTTGATGGTGGTGGCGGTCTATGGGTAAAGTTGCCGTGTTGCTGGCGGCGGTGTTTTTCCTGTTTTTGCT
CACCCAGAAACGCTGGTGAAAGTA''']

nptII = ['''ATGAGGGAAGCGGTTGGGAGATGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTG
GGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGC
AGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCG
TGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGG
CGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGC
GGCGAGTTTGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTT''']

cat = '''ATGAGAAAAATCGAAGAAGGTAAACTGGCTCGGATTGGCGAAGTTAGTAGCGGTCACAGCTTGTCTGGAAGAAGTCCATT
GAAATCGAAGTGGGTGGTAGCGAAGTTTGTTCAACCCGAATGAGATTGATGTTGATGATTTTATTTTCACTGGCGTTAAG
ACGTTTTCTTGGGCGCTATGCCCGCAGTAAATTGCTGGCAGCAAAATCAATGCAAGTAGCTGGAATGCTGATGTTGGGTT
GGTGAAGCGGTGACGAGGTGATGTATCAGGGGTATCGTCAGGTGATGATTTGACGTCACGGTTGGAAGTGGAAATTGCTC
TTGTGGTCTGGTAGTAGTTTGTAATAGTTGTGCGCAGCCTGAAGCGAA'''

