enzimas = {
    'EcoRI' : 'GAATTC',
    'BamHI' : 'GGATCC',
    'HindIII' : 'AAGCTT', 
    'PstI' : 'CTGCAG',
    'XhoI' : 'CTCGAG',
    'SalI' : 'GTCGAC',
    'SmaI' : 'CCCGGG',
    'NotI' : 'GCGGCCGC',
    'NdeI' : 'CATATG',
    'NcoI' : 'CCATGG',
}

bla = '''ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAACG
CTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGAT
CCTTGAGAGTTTTCGCCCCGAAGTTTGCGCGGTCATGTGCGCAGCGGTCGGGCTGAACAGCTTGCTGGTGAAAAGTTTGA
GGGGACGATGTCACTGGCTGAGCACAAACGGTGTAACGGGATCTTCACCTAGATCCTTTTTGATAATCTCATGACCAAAA
TCCGTTTGATTTTGATGGTGGTGGCGGTCTATGGGTAAAGTTGCCGTGTTGCTGGCGGCGGTGTTTTTCCTGTTTTTGCT
CACCCAGAAACGCTGGTGAAAGTA'''

nptII = '''ATGAGGGAAGCGGTTGGGAGATGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTG
GGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGC
AGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCG
TGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGG
CGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGC
GGCGAGTTTGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTT'''

cat = '''ATGAGAAAAATCGAAGAAGGTAAACTGGCTCGGATTGGCGAAGTTAGTAGCGGTCACAGCTTGTCTGGAAGAAGTCCATT
GAAATCGAAGTGGGTGGTAGCGAAGTTTGTTCAACCCGAATGAGATTGATGTTGATGATTTTATTTTCACTGGCGTTAAG
ACGTTTTCTTGGGCGCTATGCCCGCAGTAAATTGCTGGCAGCAAAATCAATGCAAGTAGCTGGAATGCTGATGTTGGGTT
GGTGAAGCGGTGACGAGGTGATGTATCAGGGGTATCGTCAGGTGATGATTTGACGTCACGGTTGGAAGTGGAAATTGCTC
TTGTGGTCTGGTAGTAGTTTGTAATAGTTGTGCGCAGCCTGAAGCGAA'''

genes_resistencia = {
    bla : 'B-Lactamase',
    nptII : 'Kanamicina',
    cat : 'Clorafenicol',
}

codigo_genetico = {

    'Fenilalamina' : ['UUU', 'UUC'],

    'Leucina' : ['UUA', 'UUG', 'CUU', 'CUC', 'CUA', 'CUG'],

    'Serina' : ['UCU', 'UCC', 'UCA','UCG', 'AGU', 'AGC'],

    'Tirosina' : ['UAU', 'UAC'],

    'Cisteína' : ['UGU', 'UGC'],

    'Triptofano' : ['UGG'],

    'Prolina' : ['CCU', 'CCC', 'CCA', 'CCG'],

    'Histidina' : ['CAU', 'CAC'],

    'Glutamina' : ['CAA', 'CAG'],

    'Arginina' : ['CGU', 'CGA', 'CGG', 'CGC', 'AGA', 'AGG'],

    'Isoleucina' : ['AUU', 'AUA', 'AUC'],

    'Metionina' : ['AUG'],

    'Treonina' : ['ACU', 'ACC', 'ACA', 'ACG'],

    'Aspargina' : ['AAU', 'AAC'],

    'Lisina' : ['AAA', 'AAG'],

    'Valina' : ['GUU', 'GUC', 'GUA', 'GUG'],

    'Alanina' : ['GCU', 'GCC', 'GCA', 'GCG'],

    'Ácido aspártico' : ['GAU', 'GAC'],

    'Ácido glutâmico' : ['GAA', 'GAG'],

    'Glicina' : ['GCU', 'GCG', 'GGA', 'GGG'],

    'STOP' : ['UAA', 'UAG', 'UGA']
}
