#Biblioteca criada para armazenar os genes de resistencia e seus antibióticos

bla = '''ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAACG
CTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGAT
CCTTGAGAGTTTTCGCCCCGAAGTTTGCGCGGTCATGTGCGCAGCGGTCGGGCTGAACAGCTTGCTGGTGAAAAGTTTGA
GGGGACGATGTCACTGGCTGAGCACAAACGGTGTAACGGGATCTTCACCTAGATCCTTTTTGATAATCTCATGACCAAAA
TCCGTTTGATTTTGATGGTGGTGGCGGTCTATGGGTAAAGTTGCCGTGTTGCTGGCGGCGGTGTTTTTCCTGTTTTTGCT
CACCCAGAAACGCTGGTGAAAGTA'''.replace('\n', '').upper()

nptII = '''ATGAGGGAAGCGGTTGGGAGATGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTG
GGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGC
AGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCG
TGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGG
CGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGC
GGCGAGTTTGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTT'''.replace('\n', '').upper()

cat = '''ATGAGAAAAATCGAAGAAGGTAAACTGGCTCGGATTGGCGAAGTTAGTAGCGGTCACAGCTTGTCTGGAAGAAGTCCATT
GAAATCGAAGTGGGTGGTAGCGAAGTTTGTTCAACCCGAATGAGATTGATGTTGATGATTTTATTTTCACTGGCGTTAAG
ACGTTTTCTTGGGCGCTATGCCCGCAGTAAATTGCTGGCAGCAAAATCAATGCAAGTAGCTGGAATGCTGATGTTGGGTT
GGTGAAGCGGTGACGAGGTGATGTATCAGGGGTATCGTCAGGTGATGATTTGACGTCACGGTTGGAAGTGGAAATTGCTC
TTGTGGTCTGGTAGTAGTTTGTAATAGTTGTGCGCAGCCTGAAGCGAA'''.replace('\n', '').upper()

genes_resistencia = {
    'bla': bla,
    'nptII': nptII,
    'cat': cat,
}

antibioticos = {
    'bla': 'Ampicilina',
    'nptII': 'Kanamicina',
    'cat': 'Clorafenicol',
}
