enzimas = {
    'EcoRI' : 'GAATTC',
    'BamHI' : 'GGATCC',
    'HindIII' : 'AAGCTT', 
    'PstI' : 'CTGCAG',
    'XhoI' : 'CTCGAG',
    'SalI' : 'GTCGAC',
    'SmaI / blunt' : 'CCCGGG',
    'NotI' : 'GCGGCCGC',
    'NdeI' : 'CATATG',
    'NcoI' : 'CCATGG',
    'ApaI' : 'GGGCCC',
    'KpnI' : 'GGTACC',
    'SacI' : 'GAGCTC',
    'SpeI' : 'ACTAGT',
    'XbaI' : 'TCTAGA',
    'BglII' : 'AGATCT',
    'ClaI' :   'ATCGAT',
    'EcoRV / Blunt' : 'GATATC',
    'PvuII / Blunt' : 'CAGCT',
}

bla = '''ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAACG
CTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGAT
CCTTGAGAGTTTTCGCCCCGAAGTTTGCGCGGTCATGTGCGCAGCGGTCGGGCTGAACAGCTTGCTGGTGAAAAGTTTGA
GGGGACGATGTCACTGGCTGAGCACAAACGGTGTAACGGGATCTTCACCTAGATCCTTTTTGATAATCTCATGACCAAAA
TCCGTTTGATTTTGATGGTGGTGGCGGTCTATGGGTAAAGTTGCCGTGTTGCTGGCGGCGGTGTTTTTCCTGTTTTTGCT
CACCCAGAAACGCTGGTGAAAGTA'''

nptII = '''ATGAGGGAAGCGGTTGGGAGATGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTG
GGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGC
AGGGGCGCCCGGTTCTTTTTGTCAAGACCGACCTGTCCGGTGCCCTGAATGAACTGCAGGACGAGGCAGCGCGGCTATCG
TGGCTGGCCACGACGGGCGTTCCTTGCGCAGCTGTGCTCGACGTTGTCACTGAAGCGGGAAGGGACTGGCTGCTATTGGG
CGAAGTGCCGGGGCAGGATCTCCTGTCATCTCACCTTGCTCCTGCCGAGAAAGTATCCATCATGGCTGATGCAATGCGGC
GGCGAGTTTGAGGATCGTTTCGCATGATTGAACAAGATGGATTGCACGCAGGTT'''

cat = '''ATGAGAAAAATCGAAGAAGGTAAACTGGCTCGGATTGGCGAAGTTAGTAGCGGTCACAGCTTGTCTGGAAGAAGTCCATT
GAAATCGAAGTGGGTGGTAGCGAAGTTTGTTCAACCCGAATGAGATTGATGTTGATGATTTTATTTTCACTGGCGTTAAG
ACGTTTTCTTGGGCGCTATGCCCGCAGTAAATTGCTGGCAGCAAAATCAATGCAAGTAGCTGGAATGCTGATGTTGGGTT
GGTGAAGCGGTGACGAGGTGATGTATCAGGGGTATCGTCAGGTGATGATTTGACGTCACGGTTGGAAGTGGAAATTGCTC
TTGTGGTCTGGTAGTAGTTTGTAATAGTTGTGCGCAGCCTGAAGCGAA'''

genes_resistencia = {
    bla : 'Ampicilina',
    nptII : 'Kanamicina',
    cat : 'Clorafenicol',
}

codigo_genetico = {

    'Fenilalamina' : ['TTT', 'TTC'],

    'Leucina' : ['TTA', 'TTG', 'CTT', 'CTC', 'CTA', 'CTG'],

    'Serina' : ['TCT', 'TCC', 'TCA','TCG', 'AGT', 'AGC'],

    'Tirosina' : ['TAT', 'TAC'],

    'Cisteína' : ['TGT', 'TGC'],

    'Triptofano' : ['TGG'],

    'Prolina' : ['CCT', 'CCC', 'CCA', 'CCG'],

    'Histidina' : ['CAT', 'CAC'],

    'Glutamina' : ['CAA', 'CAG'],

    'Arginina' : ['CGT', 'CGA', 'CGG', 'CGC', 'AGA', 'AGG'],

    'Isoleucina' : ['ATT', 'ATA', 'ATC'],

    'Metionina' : ['ATG'],

    'Treonina' : ['ACT', 'ACC', 'ACA', 'ACG'],

    'Aspargina' : ['AAT', 'AAC'],

    'Lisina' : ['AAA', 'AAG'],

    'Valina' : ['GTT', 'GTC', 'GTA', 'GTG'],

    'Alanina' : ['GCT', 'GCC', 'GCA', 'GCG'],

    'Ácido aspártico' : ['GAT', 'GAC'],

    'Ácido glutâmico' : ['GAA', 'GAG'],

    'Glicina' : ['GCT', 'GCG', 'GGA', 'GGG'],

    'STOP' : ['TAA', 'TAG', 'TGA']
}
